// Getters
export const GETTERS_INIT_EVENTS = "GETTERS_INIT_EVENTS";
export const GETTERS_INIT_EVENT = "GETTERS_INIT_EVENT";
export const GETTERS_TOTAL_EVENTS = "GETTERS_TOTAL_EVENTS";
export const GETTERS_ISLOADING_EVENT = "GETTERS_ISLOADING_EVENT";

// Mutations
export const MUTATE_GET_EVENTS = "MUTATE_GET_EVENTS";
export const MUTATE_ADD_EVENT = "MUTATE_ADD_EVENT";
export const MUTATE_REMOVE_EVENT = "MUTATE_REMOVE_EVENT";
export const MUTATE_UPDATE_EVENT = "MUTATE_UPDATE_EVENT";
export const MUTATE_ERROR_EVENT = "MUTATE_ERROR_EVENT";
export const MUTATE_ISLOADING_EVENT = "MUTATE_ISLOADING_EVENT";

// Actions
export const ACTION_GET_EVENTS = "ACTION_GET_EVENTS";
export const ACTION_ADD_EVENT = "ACTION_ADD_EVENT";
export const ACTION_REMOVE_EVENT = "ACTION_REMOVE_EVENT";
export const ACTION_UPDATE_EVENT = "ACTION_UPDATE_EVENT";
